version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-apache-stretch-browsers

    steps:
      - checkout
      - run: composer validate --strict
      - restore_cache:
          keys:
            - v2-php-vendor-{{ checksum "composer.lock" }}
            - v2-php-vendor-
      - run: composer install
      - save_cache:
          key: v2-php-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: mkdir ~/reports
      - run: vendor/bin/parallel-lint src tests
      - run: vendor/bin/phpunit --log-junit ~/reports/phpunit.xml
      - store-test-results:
          path: ~/reports
      - run: mkdir ~/outputs
      - run: echo "this is a log message" > ~/outputs/message.log
      - store-artifacts:
          path: ~/outputs
  security-check:
    docker:
      - image: circleci/php:7.1-apache-stretch-browsers
    steps:
      - checkout
      - run: composer validate --strict
      - restore_cache:
          keys:
            - v2-php-vendor-{{ checksum "composer.lock" }}
            - v2-php-vendor-
      - run: composer install
      - save_cache:
          key: v2-php-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: vendor/bin/security-checker security:check
  build-npm:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package-json.lock" }}
            - v1-node-modules-
      - run: npm install
      - save_cache:
          key: v1-node-modules-{{ checksum "package-json.lock" }}
          paths:
            - node-modules
      - run: npm run scss

workflows:
  version: 2
  commit:
    jobs:
      - build
      - build-npm
      - security-check

  security-check:
    triggers:
      - schedule:
          cron: "30 12 * * *"
          filters:
            branches:
              only: master
    jobs:
      - security-check
